version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: paramiq_keycloak
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm

volumes:
  keycloak_data:
